<?php
/**
 * head-theme.php — put the theme on <html> before the browser's first paint.
 *
 * WHY THIS IS INLINE, AND IN EVERY PAGE
 *
 * The theme lives in localStorage, so only JavaScript can read it, and site.js
 * — which does read it — is loaded at the BOTTOM of every page. It finished at
 * 284ms on the deployed site, long after the first paint, so anybody whose
 * saved theme differs from their operating system's setting saw the wrong
 * theme flash first and then correct itself.
 *
 * An engine file in /engine would be one source of truth, but a <script src>
 * in <head> is a render-blocking request, and paying a round trip before the
 * first paint to avoid a flash is a bad trade on a slow connection. So it is
 * inline, ~200 bytes, and this tool is what keeps 187 copies identical.
 *
 *   php tools/head-theme.php <subject> [--key=NAME] [--check]
 *   php tools/head-theme.php <path-to-site> --key=NAME [--check]
 *
 * The first argument is an Academy subject, or the path to any site directory —
 * the sibling academies (LogiFlow, QueryForge) are separate codebases with their
 * own engines, and they have this same defect, so the tool has to reach them.
 *
 * --key MATTERS AND HAS NO SAFE DEFAULT ACROSS SITES. Every academy namespaces
 * its own theme preference: academy-theme here, logiflow-theme in the C# site,
 * queryforge.theme in the SQL one, academy.theme on the landing page. They are
 * separate origins, so no two can read each other's. Point this tool at a site
 * with the wrong key and it writes a snippet that reads a value nobody ever set:
 * no error, no effect, and the flash it was meant to fix stays exactly as it was.
 *
 * doctor.php runs the --check form, so a hand-edited or newly added page cannot
 * quietly go without it.
 */

const MARKER = 'data-theme-boot';

/** The snippet itself. Kept on one line: it is the thing being compared. */
function snippet(string $key): string {
    return '<script ' . MARKER . '>/* Theme before first paint. Generated by '
         . 'tools/head-theme.php — do not edit here. */'
         . '(function(){try{var t=localStorage.getItem(' . json_encode($key) . ');'
         . 'if(t){document.documentElement.setAttribute("data-theme",t);}}catch(e){}})();'
         . '</script>';
}

$root   = dirname(__DIR__);
$target = $argv[1] ?? '';
$check  = in_array('--check', $argv, true);

$key = 'academy-theme';
foreach ($argv as $a) {
    if (str_starts_with($a, '--key=')) { $key = substr($a, 6); }
}

/* A subject name first, then a plain directory path, so the sibling academies
   outside this repository can be passed by path. */
$site = "{$root}/subjects/{$target}/site";
if (!is_dir($site)) { $site = rtrim($target, "/\\"); }

if ($target === '' || !is_dir($site)) {
    fwrite(STDERR, "usage: php tools/head-theme.php <subject|site-path> [--key=NAME] [--check]" . PHP_EOL);
    exit(2);
}

$pages = [];
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($site));
foreach ($it as $f) {
    if ($f->isFile() && strtolower($f->getExtension()) === 'html') { $pages[] = $f->getPathname(); }
}
sort($pages);

$want = snippet($key);
$stale = 0; $wrote = 0;

foreach ($pages as $page) {
    $html = file_get_contents($page);

    /* Strip any previous version of the snippet, then re-insert the current one.
       Matching on the marker attribute rather than the body means an edit to the
       snippet's contents still finds and replaces the old copy. */
    $stripped = preg_replace('~[ \t]*<script ' . MARKER . '>.*?</script>\r?\n?~s', '', $html);

    $nl  = str_contains($stripped, "\r\n") ? "\r\n" : "\n";
    $new = preg_replace('~([ \t]*)</head>~', $want . $nl . '$1</head>', $stripped, 1);

    if ($new === $html) { continue; }

    $stale++;
    if ($check) {
        echo "  stale: " . substr($page, strlen($site) + 1) . PHP_EOL;
    } else {
        file_put_contents($page, $new);
        $wrote++;
    }
}

echo PHP_EOL . "  site: {$site}" . PHP_EOL . "  key: {$key}   pages: " . count($pages);
if ($check) {
    echo "   stale: {$stale}" . PHP_EOL . PHP_EOL;
    exit($stale === 0 ? 0 : 1);
}
echo "   updated: {$wrote}" . PHP_EOL . PHP_EOL;
