<?php
/**
 * head-brand.php — put this subject's accent colour on the page before the
 * browser's first paint.
 *
 * WHY THIS IS INLINE, AND IN EVERY PAGE
 *
 * The same trade head-theme.php makes, and the reasoning is worth repeating
 * because the obvious alternative looks cleaner and is worse. engine/style.css
 * is byte-identical across every subject by design: sync-engine.php copies it
 * in, doctor.php fails the build when a copy has drifted. So the accent cannot
 * be written there without teaching the shared engine the names of its
 * subjects — and then a fourth subject means editing the engine to add one.
 *
 * The other alternative is a per-subject assets/brand.css. That is a
 * render-blocking <link> in <head>: a whole round trip before the first paint,
 * spent carrying six colours. Inline is ~250 bytes with no request at all, and
 * unlike the theme snippet it needs no JavaScript, so it also survives with
 * scripting off.
 *
 *   php tools/head-brand.php <subject> [--check]
 *
 * Subjects only, deliberately — unlike head-theme.php, which takes a path so it
 * can reach the sibling academies. Those have their own engines and their own
 * palettes (the C# site's .NET purple is correct there, not a leftover), and
 * they have no subject.js for this tool to read a `brand` block out of.
 *
 * doctor.php runs the --check form, so a hand-edited or newly added page cannot
 * quietly go without it, and a colour changed in subject.js but never stamped
 * is caught before it ships.
 */

const MARKER = 'data-brand';

/**
 * Pull the `brand` block out of subject.js.
 *
 * Reading JavaScript with a regex is only tolerable because the shape is fixed
 * and the failure is loud: anything unexpected exits non-zero rather than
 * falling back to a default. A silent fallback here would paint every subject
 * the engine's .NET purple and look exactly like success.
 */
function brandOf(string $subjectJs): array {
    $src = file_get_contents($subjectJs);

    if (!preg_match('~\bbrand:\s*\{(.+?)\n\s*\},~s', $src, $m)) {
        fwrite(STDERR, "  subject.js has no brand block — see subjects/java/site/assets/subject.js" . PHP_EOL);
        exit(2);
    }

    $out = [];
    foreach (['light', 'dark'] as $theme) {
        if (!preg_match('~\b' . $theme . ':\s*\{([^}]*)\}~', $m[1], $t)) {
            fwrite(STDERR, "  brand block has no `{$theme}` theme. Both are required: engine/style.css"
                         . " sets --brand once for light and twice for dark, so a missing half leaves"
                         . " that half on the engine default." . PHP_EOL);
            exit(2);
        }
        foreach (['base', 'soft', 'ink', 'lift'] as $slot) {
            if (!preg_match('~\b' . $slot . ':\s*"(#[0-9a-fA-F]{3,8})"~', $t[1], $c)) {
                fwrite(STDERR, "  brand.{$theme} has no `{$slot}` colour" . PHP_EOL);
                exit(2);
            }
            $out[$theme][$slot] = $c[1];
        }
    }
    return $out;
}

/**
 * The snippet itself. Kept on one line: it is the thing being compared.
 *
 * All THREE of the engine's --brand declarations have to be answered — light,
 * the prefers-color-scheme media query, and the explicit [data-theme="dark"]
 * toggle — and the selectors have to match the engine's character for
 * character. Same specificity, later in the document, so these win; write
 * `:root` where the engine wrote `:root:not([data-theme="light"])` and the
 * engine's rule is the more specific one and keeps its purple in dark mode.
 */
function snippet(array $b): string {
    $vars = static fn (array $t): string =>
        '--brand:' . $t['base'] . ';--brand-soft:' . $t['soft'] . ';--brand-ink:' . $t['ink']
        . ';--brand-lift:' . $t['lift'];

    return '<style ' . MARKER . '>/* Accent before first paint. Generated by '
         . 'tools/head-brand.php from assets/subject.js — do not edit here. */'
         . ':root{' . $vars($b['light']) . '}'
         . '@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){' . $vars($b['dark']) . '}}'
         . ':root[data-theme="dark"]{' . $vars($b['dark']) . '}'
         . '</style>';
}

$root    = dirname(__DIR__);
$subject = $argv[1] ?? '';
$check   = in_array('--check', $argv, true);

$site = "{$root}/subjects/{$subject}/site";

if ($subject === '' || !is_dir($site)) {
    fwrite(STDERR, "usage: php tools/head-brand.php <subject> [--check]" . PHP_EOL);
    exit(2);
}
if (!is_file($site . '/assets/subject.js')) {
    fwrite(STDERR, "  {$subject} has no assets/subject.js" . PHP_EOL);
    exit(2);
}

$pages = [];
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($site));
foreach ($it as $f) {
    if ($f->isFile() && strtolower($f->getExtension()) === 'html') { $pages[] = $f->getPathname(); }
}
sort($pages);

$brand = brandOf($site . '/assets/subject.js');
$want  = snippet($brand);
$stale = 0; $wrote = 0;

foreach ($pages as $page) {
    $html = file_get_contents($page);

    /* Strip any previous version, then re-insert the current one. Matching on
       the marker attribute rather than on the body means a changed colour still
       finds and replaces the old copy instead of stacking a second block. */
    $stripped = preg_replace('~[ \t]*<style ' . MARKER . '>.*?</style>\r?\n?~s', '', $html);

    $nl = str_contains($stripped, "\r\n") ? "\r\n" : "\n";

    /* ANCHOR: immediately after the last stylesheet <link>, NOT before </head>.
       Two reasons, and the second one cost a broken gate to find.

       The requirement: this block overrides tokens engine/style.css already
       set, at the same specificity, so it only wins by coming later. Anywhere
       after the last stylesheet satisfies that, and nothing before it does.

       The trap: head-theme.php also stamps into this head, and it anchors on
       </head> — it strips its snippet and re-inserts it immediately before the
       close tag. Two tools anchored on </head> take turns evicting each other
       from the spot, so each one's --check then reports every page as stale,
       forever, and doctor fails on whichever ran first. Anchoring on the thing
       this block actually depends on leaves that spot to head-theme.php and
       makes both tools idempotent in either order. */
    if (preg_match_all('~[ \t]*<link rel="stylesheet"[^>]*>\r?\n?~', $stripped, $ss, PREG_OFFSET_CAPTURE)) {
        $last = end($ss[0]);
        $at   = $last[1] + strlen($last[0]);
        $new  = substr($stripped, 0, $at) . $want . $nl . substr($stripped, $at);
    } else {
        /* No stylesheet to override. Nothing here is load-bearing then, but
           stamping anyway keeps every page carrying the block, which is what
           doctor's site/brand check asserts. */
        $new = preg_replace('~([ \t]*)</head>~', $want . $nl . '$1</head>', $stripped, 1);
    }

    if ($new === $html) { continue; }

    $stale++;
    if ($check) {
        echo "  stale: " . substr($page, strlen($site) + 1) . PHP_EOL;
    } else {
        file_put_contents($page, $new);
        $wrote++;
    }
}

echo PHP_EOL . "  site: {$site}" . PHP_EOL
   . "  brand: " . $brand['light']['base'] . " light / " . $brand['dark']['base'] . " dark"
   . "   pages: " . count($pages);
if ($check) {
    echo "   stale: {$stale}" . PHP_EOL . PHP_EOL;
    exit($stale === 0 ? 0 : 1);
}
echo "   updated: {$wrote}" . PHP_EOL . PHP_EOL;
